export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const AUTHENTICATED_USER = "AUTHENTICATED_USER";
export const LOGOUT = "LOGOUT";

export const CLEAN_ALERT = "CLEAN_ALERT";
export const SHOW_ALERT = "SHOW_ALERT";

export const UPLOAD_FILE_SUCCES = "UPLOAD_FILE_SUCCES";
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR";

export const CREATE_LINK_SUCCESS = "CREATE_LINK_SUCCESS";
export const CREATE_LINK_ERROR = "CREATE_LINK_ERROR";
